Repository ai-dynamo/modelexpress, pull requests merged in 2025-10, with the labels that each got.

#83 feat: bring dockerfile into compliance with OSRB (#81)
  .dockerignore
  .gitignore
  Dockerfile
Labels: feat, size/S

#86 feat: move versioning and dependency refs to top Cargo.toml
  .gitignore
  Cargo.lock
  Cargo.toml
  modelexpress_client/Cargo.toml
  modelexpress_common/Cargo.toml
  modelexpress_server/Cargo.toml
  workspace-tests/Cargo.toml
Labels: feat, size/M

#87 fix: Update container name and version
  helm/Chart.yaml
  helm/test-values.yaml
  helm/values-production.yaml
  helm/values.yaml
Labels: fix, size/S

#89 fix: Rename Helm Chart to Modelexpress
  helm/Chart.yaml
  helm/README.md
  helm/deploy.sh
  helm/templates/NOTES.txt
  helm/templates/_helpers.tpl
  helm/templates/deployment.yaml
  helm/templates/ingress.yaml
  helm/templates/pvc.yaml
  helm/templates/service.yaml
  helm/templates/serviceaccount.yaml
  helm/templates/tests/test-connection.yaml
  helm/values-production.yaml
Labels: fix, size/L

#94 fix: add spdx headers to helm chart files
  .github/workflows/common.ps1
  .github/workflows/copyright-check.ps1
  .github/workflows/copyright-checks.yml
  helm/.helmignore
  helm/Chart.yaml
  helm/README.md
  helm/deploy.sh
  helm/templates/NOTES.txt
  helm/templates/_helpers.tpl
  helm/templates/deployment.yaml
  helm/templates/ingress.yaml
  helm/templates/pvc.yaml
  helm/templates/service.yaml
  helm/templates/serviceaccount.yaml
  helm/templates/tests/test-connection.yaml
  helm/test-values.yaml
  helm/values-development.yaml
  helm/values-production.yaml
  helm/values.yaml
  modelexpress_common/proto/api.proto
  modelexpress_common/proto/health.proto
  modelexpress_common/proto/model.proto
Labels: fix, size/XL

#97 fix: add spdx headers to helm chart files (#94)
  .github/workflows/common.ps1
  .github/workflows/copyright-check.ps1
  .github/workflows/copyright-checks.yml
  helm/.helmignore
  helm/Chart.yaml
  helm/README.md
  helm/deploy.sh
  helm/templates/NOTES.txt
  helm/templates/_helpers.tpl
  helm/templates/deployment.yaml
  helm/templates/ingress.yaml
  helm/templates/pvc.yaml
  helm/templates/service.yaml
  helm/templates/serviceaccount.yaml
  helm/templates/tests/test-connection.yaml
  helm/test-values.yaml
  helm/values-development.yaml
  helm/values-production.yaml
  helm/values.yaml
  modelexpress_common/proto/api.proto
  modelexpress_common/proto/health.proto
  modelexpress_common/proto/model.proto
Labels: fix, size/XL

#92 fix: Add references to new release image
  helm/README.md
  helm/values-development.yaml
  k8s-deployment.yaml
Labels: fix, size/S
