Repository ai-dynamo/modelexpress, pull requests merged in 2025-09, with the labels that each got.

#70 fix: remove deprecated k8s documentation for mx
  docs/dynamo-k8s.md
Labels: fix, size/L

#73 feat: add support for name mapping back to HF id
  modelexpress_common/src/cache.rs
Labels: feat, size/M

#69 feat: Add helm charts for deploying model express server
  Cargo.lock
  Cargo.toml
  helm/.helmignore
  helm/Chart.yaml
  helm/README.md
  helm/deploy.sh
  helm/templates/NOTES.txt
  helm/templates/_helpers.tpl
  helm/templates/deployment.yaml
  helm/templates/ingress.yaml
  helm/templates/pvc.yaml
  helm/templates/service.yaml
  helm/templates/serviceaccount.yaml
  helm/templates/tests/test-connection.yaml
  helm/test-values.yaml
  helm/values-development.yaml
  helm/values-production.yaml
  helm/values.yaml
  k8s-deployment.yaml
Labels: feat, size/XXL

#74 fix: ensure tilde expands to system home directory
  .pre-commit-config.yaml
  modelexpress_common/src/cache.rs
  modelexpress_common/src/lib.rs
  modelexpress_common/src/providers/huggingface.rs
Labels: fix, size/L

#75 feat: add `get_model_path` api for dynamo integration
  Cargo.lock
  modelexpress_client/src/lib.rs
  modelexpress_common/Cargo.toml
  modelexpress_common/src/download.rs
  modelexpress_common/src/providers.rs
  modelexpress_common/src/providers/huggingface.rs
Labels: feat, size/L

#81 feat: bring dockerfile into compliance with OSRB
  .dockerignore
  .gitignore
  Dockerfile
Labels: feat, size/S

#80 docs: Update README.md with clearer Kubernetes documentation
  README.md
Labels: docs, size/M
